apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  annotations:
    serverless.openshift.io/default-enable-http2: "true"
spec:
  ingress:
    kourier:
      enabled: true
  config:
    domain:
      dev.apps.sno.codemint.ch: | 
        selector:
          router: dev
      prod.apps.sno.codemint.ch: | 
        selector:
          router: prod
