apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
  labels:
    router: dev
spec:
  template:
    spec:
      containers:
      - image: docker.io/openshift/hello-openshift

