apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-prod
  namespace: default
  labels:
    router: prod
spec:
  template:
    spec:
      containers:
      - image: docker.io/openshift/hello-openshift

