---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: ingress-dev
  namespace: openshift-ingress-operator
spec:
  replicas: 1
  routeSelector:
    matchLabels:
      router: dev
  domain: "dev.apps.sno.codemint.ch"
  endpointPublishingStrategy:
    type: HostNetwork
    hostNetwork:
      httpPort: 8081
      httpsPort: 8444
      statsPort: 1937
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: ingress-prod
  namespace: openshift-ingress-operator
spec:
  replicas: 1
  routeSelector:
    matchLabels:
      router: prod
  domain: "prod.apps.sno.codemint.ch"
  endpointPublishingStrategy:
    type: HostNetwork
    hostNetwork:
      httpPort: 8082
      httpsPort: 8445
      statsPort: 1938
---
